Redesign UI
owdex/owdex pull request #57
Opened 2023-04-09 20:31 UTC by alexmshepherd

This is a complete UI overhaul. @4censord what do you think? Closes #29.

2023-04-09 20:40 UTC, alexmshepherd commented
This is live at [the canonical instance](https://owdex.com/) right now.

2023-04-10 13:20 UTC, 4censord commented
I will get to reviewing this in detail at the earliest on Tuesday.

On first look I like it.

2023-04-12 14:02 UTC, 4censord requested changes
We should talk about tabs/spaces in the HTML templates. I don't care about which one we do, is just should be consistent across files.

2023-04-12 15:21 UTC, alexmshepherd commented on owdex/linkmanager.py
> +                raise
Yep, agreed.

2023-04-12 15:23 UTC, alexmshepherd commented on owdex/users.py
> +    elif action == "signup":
Got it. I'll try to rework this.

2023-04-12 15:24 UTC, alexmshepherd commented
> Also, imo there should be a backlink from the error pages to either the homepage or the page from which they originally came

Agreed.

2023-04-12 15:29 UTC, alexmshepherd commented
> tabs/spaces in the HTML templates

I wasn't aware this wasn't consistent. I'll work on improving pre-commit. My preference is for tabs.

2023-04-12 19:29 UTC, alexmshepherd commented on owdex/users.py
> +    elif action == "signup":
Resolved by [f442bdd](https://github.com/owdex/owdex/pull/57/commits/f442bdd695446243c8dcb8503c4d4ce9b92bb8d2).

2023-04-12 19:32 UTC, alexmshepherd commented on owdex/linkmanager.py
> +                raise
Resolved by [0cec78f](https://github.com/owdex/owdex/pull/57/commits/0cec78f1e141e7412abda4bc4497f182c457ca2a).

2023-04-12 20:03 UTC, 4censord approved these changes

2023-04-12 20:03 UTC, 4censord commented on owdex/users.py
I like this more, it feels cleaner. 
Thank you

2023-04-12 20:07 UTC, merged

2023-04-12 20:37 UTC, alexmshepherd commented
@4censord See #69 (yes I know).